schema = 1

[port]
name = "brute_tigrex"
host_species = 75
pac = "brute_tigrex.bin"
replace = [
    77,
]

[source]
model = 5248

[build]
source_skeleton = true
skin = "source"

[clips.charge]
source = 61
frames = 382
loop = false
label = "crazy forward charge"

[moves.charge]
main = 2
sub = 8
clip = "charge"
